Return unknown prediction message
c22-cb02/siloka-backend pull request #11
Opened 2022-06-15 07:43 UTC by RadhiansyaZ

### Changes
- Return unknown message "We don't understand what you mean. Could you repeat your question, please?" if the prediction `accuracy` below .5

2022-06-15 10:21 UTC, dnswd requested changes
Kayaknya aman sih, cuma gw ada satu hal yg gw gak yakin. Boleh dicek dulu gak sebelum merge?

2022-06-15 10:21 UTC, dnswd commented on index.js
>        const predictionData = response.data;
Ini udah yakin pasti `Number`?

2022-06-16 04:20 UTC, gpersable approved these changes

2022-06-16 04:41 UTC, dnswd approved these changes
LGTM

2022-06-16 04:41 UTC, merged